[discord]
# 大獎、看門狗重啟、水道異常告警頻道
alert_webhook = https://discord.com/api/webhooks/1488034466554446007/q-Cf_z874KRD2gtYH3jgJ8X5nqyFU8NU7VGTSgvkuOhm2S61WzGLj3_lDGEqkkXc52OU
# 每 30 分鐘收益與日預估報表頻道
report_webhook = https://discord.com/api/webhooks/1488032836219834429/cN7Bi-ro6QtvJIGiqb24Z0KeLALetKuTdzpTtj2Q2Cyq74MnKMA5uvUWLPneiZ--mZFq

[custom_stats]
# 格式：英文原名 #中文標籤 (程式會自動偵測英文並顯示中文)
item1 = Seven Years Bad Luck #七年
item2 = The Apothecary #藥劑師
item3 = The Black Barya #黑幣

[settings]
# 是否關閉水道告警推播 (true: 不推播 / false: 滿5次即告警)
aqueduct_only = false
